[project]
name = "citeline"
version = "0.1.0"
description = "Citation prediction system"
authors = [
  {name = "Benjamin Basseri", email = "bbasseri@fas.harvard.edu"}
]
dependencies = []

[tool.black]
line-length = 120

[tool.pytest.ini_options]
pythonpath = [
  "."
]