[project]
name = "citeline"
version = "0.1.0"
description = "Citation prediction system"
authors = ["Benjamin Basseri <bbasseri@fas.harvard.edu>"]
dependencies = []

[tool.black]
line-length = 100

[tool.pytest.ini_options]
pythonpath = [
  "."
]