findings = {
    "10.1088/0004-637X/767/1/49": [
        "Detection of Ne VIII and O VI absorption line systems at redshifts z_abs = 0.68381, 0.70152, and 0.72478 in the quasar PG1148+549 spectrum.",
        "Identification of multiphase systems including hot gas (T ≈ 10^5.7 K) producing Ne VIII and O VI, and cooler phases (≈10^4 K) with densities n_H ≈ 10^-4 cm^-3.",
        "Measurement of gas metallicity in the cool phase ranging from Z = 0.3 Z_⊙ to supersolar values.",
        "Observation of small sizes (<4 kpc) for the cool clouds, suggesting they are likely to expand and dissipate.",
        "Determination of a high Ne VIII redshift density, dN/dz ≈ 7^{+7}_{-3}, indicating a large number of these clouds per galaxy and a large effective absorption cross section (≳100 kpc).",
        "Discovery of a star-forming galaxy at the redshift of the z_abs = 0.72478 system, located at an impact parameter of 217 kpc.",
        "Conclusion that multiphase absorbers like these Ne VIII systems are significant reservoirs of baryons and metals in the circumgalactic media of galaxies.",
    ],
    "10.1086/163605": [
        "Monte Carlo computations of X-ray secondary electron heating, ionization, and excitation in H and He gas for quasar emission-line clouds were performed.",
        "The fraction of energy deposited as heat, ionization, or excitation is sensitive to the background ionization fraction x = n(H+)/n(Htot).",
        "Analytic fits for energy deposition fractions are provided for ionization fractions x in the range 0.0001 to 1 and primary electron energies up to several keV.",
        "Secondary electron effects significantly impact temperature, ionization state, and line emissivities in X-ray photoionized clouds at large depths.",
        "In both broad-line and narrow-line clouds, emission lines sensitive to energy budget and electron density are strongly affected by secondary processes.",
        "The study highlights the importance of including secondary ionization and heating in photoionization models of AGN emission-line regions.",
        "At low ionization fractions (x < 0.1), a substantial portion of a primary electron's energy goes into secondary ionization and excitation rather than heat.",
        "Collisional ionization of H and He produces high-energy secondary electrons, influencing the energy distribution in the gas.",
        "The results correct previous underestimations of secondary electron effects in interstellar and quasar cloud models.",
        "Secondary processes are critical for accurately modeling emission lines like Lyman-alpha, [O III], and [Ne III] in photoionized clouds.",
    ],
    "10.1111/j.1365-2966.2009.14750.x": [
        "Models of the chemical evolution of the Galaxy are extended to include radial migration of stars and flow of gas through the disc.",
        "The models track the production of both iron and α-elements.",
        "A model is chosen that provides an excellent fit to the metallicity distribution of stars in the Geneva-Copenhagen survey (GCS) of the solar neighbourhood.",
        "The model provides a good fit to the distribution of GCS stars in the age-metallicity plane, although this plane was not used in the fitting process.",
        "The model's star formation rate is monotonically declining, yet its disc naturally splits into an α-enhanced thick disc and a normal thin disc.",
        "The model's distribution of stars in the ([O/Fe], [Fe/H]) plane resembles that of Galactic stars, displaying a ridge line for each disc.",
        "The thin-disc's ridge line is entirely due to stellar migration, with characteristic variation of stellar angular momentum along it.",
        "Radial mixing of stellar populations with high σz from inner regions of the disc to the solar neighbourhood explains the steeper increase of σz with age than predicted by theory.",
        "The metallicity gradient in the interstellar medium is predicted to be steeper than in earlier models, but appears to be in good agreement with data for both our Galaxy and external galaxies.",
        "The models are inconsistent with a cut-off in the star formation rate at low gas surface densities.",
        "The absolute magnitude of the disc is given as a function of time in several photometric bands, and radial colour profiles are plotted for representative times.",
        "The dichotomy between the thin and thick discs arises naturally from the model without requiring breaks in star formation history or accretion events.",
        "The model reproduces the observed correlations between metallicity and stellar kinematics in the solar neighbourhood.",
        "The vertical density profile of the disc can be represented as the sum of two exponentials, corresponding to the thin and thick discs.",
        "The model predicts a steeper metallicity gradient in the gas than in the stars, due to radial gas flows and mixing.",
        "The age-velocity dispersion relation in the solar neighbourhood is explained by radial migration bringing stars born in the inner disc to the solar neighbourhood.",
    ],
    "10.1086/309975": [
        "The comoving luminosity density of the universe increases with redshift in all three observed wave bands (2800 A, 4400 A, and 1 mu m).",
        "For a (q0 = 0.5, Omega = 1.0) cosmological model, the comoving luminosity density increases as (1 + z)^2.1 +/- 0.5 at 1 mu m, (1 + z)^2.7 +/- 0.5 at 4400 A, and (1 + z)^3.9 +/- 0.75 at 2800 A.",
        "The exponents for luminosity density evolution are reduced by 0.43 and 1.12 for (0.05, 0.1) and (-0.85, 0.1) cosmological models, respectively.",
        "The observed luminosity density evolution can be modeled by an actively evolving stellar population with a Salpeter initial mass function (IMF) extending to 125 M⊙ and a star formation rate declining as tau^-2.5.",
        "A Scalo IMF extending to the same mass limit produces too many long-lived low-mass stars and does not fit the observed data as well.",
        "The rapid evolution of the star formation rate and comoving luminosity density agrees with conclusions from analyses of the evolving metallicity of the universe.",
        "The physical luminosity density at short wavelengths has likely declined by 2 orders of magnitude since z ~ 1.",
        "The global star formation rate at z ~ 1 was 15 times higher for (0.5, 1.0), 11 times higher for (0.05, 0.1), and 7 times higher for (-0.85, 0.1) cosmological models, with uncertainties of about 0.22 in the log.",
        "The physical luminosity density at 2800 Å has declined by a factor of 60–170 since z ~ 1 for a (0.5, 1.0) model, with a factor of 2 reduction in the extreme (-0.85, 0.1) model.",
    ],
    "10.1086/300959": [
        "The study finds a shallower decline in the universal rest-frame ultraviolet (UV) luminosity density from z=1 to the present, approximately (1+z)^1.5 for q_0=0.5, contradicting the steeper evolution reported by Lilly et al.",
        "The results suggest that galaxy formation continues smoothly to the present time rather than peaking at z=1, with much of the current formation occurring in smaller galaxies.",
        "The UV luminosity density at low redshifts is considerably higher than previously estimated by Lilly et al., aligning more closely with the local UV luminosity density determined by Treyer et al.",
        "The analysis uses a deep, multi-color spectroscopic redshift survey to avoid extrapolation issues present in previous studies, providing more accurate rest-frame UV luminosity measurements.",
        "The study compares luminosity functions at different rest-frame wavelengths (1700 Å, 2250 Å, 2750 Å) and finds only weak sensitivity to wavelength choice, supporting the robustness of the results.",
        "The 2500 Å rest-frame luminosity density evolution is well-described by a (1+z)^1.5 power law, indicating a slower decline in star formation activity than previously thought.",
        "Comparisons with the Treyer et al. local UV sample show consistent luminosity densities, further supporting the shallower evolution slope.",
        "The study highlights discrepancies with the Lilly et al. CFRS analysis, attributing them to methodological differences and extrapolation uncertainties in the CFRS data.",
        "The rest-frame red luminosity (8000 Å) shows minimal evolution from z=0.5 to z=1, contrasting with the more significant evolution observed in the UV.",
        "The findings imply that the bulk of star formation has occurred at more recent times, challenging the notion that the peak epoch of galaxy formation was at z=1.",
    ],
    "10.1086/311708": [
        "A flat distribution of the comoving UV luminosity density is statistically indistinguishable from a peaked distribution at z~1.5 when errors, especially sampling error, are properly accounted for.",
        "Applying a uniform surface brightness cut reveals that the UV luminosity density from high intrinsic surface brightness regions increases by almost 2 orders of magnitude from z~0 to z~5.",
        "There exists a population of high-redshift objects with very high star formation rates that are not present at low redshifts.",
        "The peak of star formation likely occurs beyond z>2, contrary to previous suggestions of a peak at z~1.5.",
        "Sampling error dominates the uncertainty in UV luminosity density measurements, and previous analyses underestimated this uncertainty.",
        "The M98 Lyman break galaxy selection method may miss up to 50% of high-redshift galaxies in the Hubble Deep Field.",
        "Cosmological surface brightness dimming significantly affects UV luminosity density measurements, with high-redshift observations sampling only the highest surface brightness regions.",
        "The ratio of UV luminosity density from high surface brightness regions to total UV luminosity density is much higher at high redshifts than at low redshifts, suggesting a strongly increasing UV luminosity density with redshift.",
    ],
    "10.1051/0004-6361/201834371": [
        "Detection of proper motion anomalies (PMa) in 30% of the 6741 nearby stars within 50 parsecs, indicating the presence of stellar or substellar companions.",
        "Confirmation that Proxima Centauri is gravitationally bound to α Centauri using Gaia DR2 and HIPPARCOS data.",
        "Upper mass limits of 0.1-0.3 Jupiter masses for potential planets orbiting Proxima Centauri between 1 and 10 astronomical units.",
        "Recovery of the masses of known companions of stars such as ɛ Eridani, ɛ Indi, Ross 614, and β Pictoris.",
        "Detection of a possible planet of a few Jovian masses orbiting τ Ceti.",
        "Identification of a bimodal distribution in companion masses, with peaks around 1-2 and 50-100 Jupiter masses per square root of astronomical unit, suggesting a brown dwarf desert.",
        "Measurement of tangential velocity anomalies at a median accuracy of 1.0 meter per second per parsec of distance using Gaia DR2.",
        "Demonstration of Gaia's complementarity to radial velocity and transit techniques for detecting long-period orbital companions.",
        "Analysis of the binarity fraction as a function of primary star mass, showing a steep decrease for very low-mass stars (below 0.35 solar masses).",
        "Application of the PMa technique to resolved binary stars like 61 Cyg AB, HD 173739+HD 173740, and HD 79210+HD 79211, confirming mass ratios and detecting potential third bodies.",
        "Constraints on the presence of additional planets in systems like β Pictoris, excluding planets more massive than 5 Jupiter masses beyond 4 astronomical units.",
        "Detection of significant PMa in white dwarfs such as LAWD 37 and GD 140, suggesting the presence of planetary companions.",
        "Observation of a possible Saturn-mass planet orbiting Ross 128 between 1 and 10 astronomical units.",
        "Exclusion of planets more massive than 2 Jupiter masses around the white dwarf Wolf 28 between 3 and 10 astronomical units.",
        "Detection of a PMa in the metal-poor star HD 103095, setting limits on possible planetary companions.",
        "Identification of a potential bound companion to 51 Peg at 44 astronomical units, in addition to the known hot Jupiter.",
    ],
    "10.3847/1538-4357/aa6007": [
        "The CGM of field L* galaxies exhibits a declining H I surface density with impact parameter R⊥ at >99.5% confidence.",
        "The transmission of ionizing radiation through CGM gas alone is 70 ± 7%.",
        "The metallicity distribution function of the cool CGM is unimodal with a median of 10^-0.51 Z⊙ and a 95% interval ≈1/50 Z⊙ to >3 Z⊙.",
        "The incidence of metal-poor (<1/100 Z⊙) gas is low, implying any such gas discovered along quasar sightlines is typically unrelated to L* galaxies.",
        "An unexpected increase in gas metallicity with declining N_HI (at >99.9% confidence) and, therefore, also with increasing R⊥ was found; the high metallicity at large radii implies early enrichment.",
        "A non-parametric estimate of the cool CGM gas mass is M_CGM^cool = (9.2 ± 4.3) × 10^10 M⊙, which together with new mass estimates for the hot CGM may resolve the galactic missing baryons problem.",
        "The CGM of field L* galaxies is generally enriched above ~10% solar, with a broad metallicity distribution indicating significant scatter.",
        "At least a subset of the CGM surrounding field L* galaxies has super-solar metallicity, with 15% of systems having 90% of their metallicity PDFs above solar.",
        "An anti-correlation between N_HI and metallicity was observed, suggesting higher metallicity at lower N_HI and larger impact parameters.",
        "The cool CGM gas mass estimate suggests it is a major reservoir of baryons, potentially rivaling the condensed baryonic matter in galaxies.",
    ],
    "10.1093/mnras/283.4.1388": [
        "The Lyman decrement associated with HI in QSO absorption systems provides a distinctive feature for identifying galaxies at z > 2.5.",
        "Colour criteria sensitive to the Lyman continuum break can successfully identify star-forming galaxies at 3 < z < 3.5, as confirmed by Keck spectroscopy.",
        "The Hubble Deep Field (HDF) observations allow for statistical constraints on the redshift distribution of galaxies to fainter limits than current spectroscopic limits.",
        "A model of HI cosmic opacity as a function of redshift, including Lyman series scattering and Lyman continuum absorption, was developed.",
        "Stellar population synthesis models with varied ages, metallicities, dust contents, and redshifts were used to derive robust colour selection criteria for high-redshift galaxies.",
        "A sample of star-forming galaxies at 2 < z < 4.5 was constructed from HDF images using these colour criteria.",
        "The colour criteria effectively selected galaxies at 2.6 < z < 3.2 without contamination from low-redshift galaxies (0 < z < 1.4).",
        "The ultraviolet dropout technique enables investigation of cosmic star and element formation in the early Universe.",
        "A lower limit to the heavy element ejection rate from Type II supernovae at <z> = 2.75 was set at ~3.6 x 10^-4 M_solar yr^-1 Mpc^-3 (for q_0 = 0.5, H_0 = 50 km s^-1 Mpc^-1).",
        "The metal ejection rate at <z> = 2.75 is 3 times higher than the local value but 4 times lower than the rate at z ~ 1.",
        "At <z> = 4, the lower limit to the cosmic metal ejection rate is ~3 times lower than the <z> = 2.75 value.",
        "The results have implications for models of galaxy formation and the chemical enrichment and ionization history of the intergalactic medium.",
    ],
    "10.48550/arXiv.2203.02041": [
        "The paper reviews the evolution of stars and gas in galaxies, focusing on chemical and photometric evolution.",
        "It discusses the initial mass function (IMF) and its variations in different regions and times, noting that the local IMF can be approximated by power-law segments with different slopes for different mass ranges.",
        "The study highlights the importance of star formation rates (SFR) and factors affecting them, such as gas density and dynamical processes.",
        "Stellar evolution beyond the main sequence is detailed, including the contributions of stars of different masses to nucleosynthesis and galactic enrichment.",
        "The paper presents analytical and numerical methods for modeling chemical evolution, including the effects of gas flows and infall.",
        "It addresses the 'G-dwarf problem' in the Solar neighborhood, proposing solutions such as infall of metal-poor gas and pre-enrichment by halo stars.",
        "The study examines relative abundances of elements, distinguishing between primary and secondary elements and their production in stars of different masses.",
        "The paper explores abundance gradients in spheroidal systems, attributing them to dissipative collapse, IMF gradients, and finite stellar lifetimes.",
        "It investigates the metallicity-mass relation for elliptical galaxies, suggesting mechanisms like supernova-driven winds and bursts of star formation in merging subsystems.",
        "The role of the intergalactic medium and gas loss from galaxies is discussed, including the ejection of metals and overall gas loss.",
        "Abundance gradients in disks are analyzed, with infall and radial gas flows proposed as key factors.",
        "The paper outlines approaches to photometric evolution, including population synthesis, evolutionary models, and analytical approximations.",
        "It describes the evolution of a single generation of stars, covering content and luminosity, remnants of dead stars, and the ratio of giants to dwarfs in the light.",
        "The study predicts the evolution of luminosity and colors in elliptical galaxies, emphasizing their implications for cosmological tests like the Hubble diagram.",
        "The paper concludes with an analysis of UBV colors of normal galaxies, linking them to star formation rates and galaxy types.",
    ],
    "10.1086/310829": [
        "Incorporating near-infrared data with Hubble Deep Field (HDF) optical data reduces photometric redshift uncertainty by approximately 40% and removes systematic uncertainties in the redshift range 1 < z < 2.",
        "The global star formation rate (SFR) increases by a factor of 12 from redshift zero to a peak at z ~ 1.5, then decreases monotonically beyond z > 1.5.",
        "Photometric redshifts derived from combined optical and near-infrared data show a dispersion of σ_z = 0.06, significantly improving accuracy in the 1 < z < 2 range compared to optical-only methods.",
        "The comoving ultraviolet (2800 Å) luminosity density, used as a proxy for SFR, peaks at z ~ 1.5 and declines at higher redshifts, bridging the gap between previous studies at z < 1 and z > 2.",
        "The derived star formation history aligns with theoretical models by White and Frenk and predictions by Pei and Fall based on the evolving H I content of Lyα QSO absorption systems.",
        "The HDF J-band selected sample (J < 23.5) probes rest-frame optical wavelengths for galaxies at 1 < z < 2, analogous to the I-band selection of the Canada-France Redshift Survey at lower redshifts.",
        "The metal enrichment rate (MER) evolution, derived from UV luminosity densities, is consistent across spectroscopic, photometric, and Lyman break galaxy samples, peaking at z ~ 1.5.",
        "The study highlights the importance of near-infrared data for accurate photometric redshift estimation in the 1 < z < 2 range, where optical data alone are insufficient due to the 4000 Å break shifting out of the optical window.",
    ],
    "10.1086/341818": [
        "The universal rest-frame ultraviolet luminosity density evolves as (1+z)^1.7±1.0 for a flat lambda (Ωm0=0.3, Ωλ0=0.7) cosmology.",
        "The evolution follows a steeper slope of (1+z)^2.4±1.0 for an Einstein-de Sitter cosmology.",
        "The study uses multicolor data (U'AB, BAB, VAB=24.5) and spectroscopic redshifts from the Hawaii Survey Fields and the Hubble Deep Field.",
        "Galaxies were selected based on rest-frame ultraviolet (2500 Å) magnitudes across the redshift range z=1.5 to the present.",
        "The luminosity functions (LFs) were constructed using both the traditional Vmax method and the Page-Carrera method, yielding consistent results.",
        "Schechter function parameterizations of the LFs were performed with fixed faint-end slopes of α=-1.0 and α=-1.5 to bound the range of possible slopes.",
        "The choice of cosmology affects the LF parameters, with a flat lambda cosmology resulting in decreased M* and φ* compared to an Einstein-de Sitter cosmology.",
        "The rest-frame ultraviolet luminosity density was calculated by integrating the LFs, showing similar results whether summing over magnitude bins or integrating the Schechter function analytically.",
        "The study finds that more star formation has occurred in recent times than previously suggested, based on the derived luminosity density evolution.",
        "Comparisons with previous surveys (e.g., Lilly et al. 1996, Sullivan et al. 2000) show discrepancies attributed to differences in sample selection, depth, and methodology.",
        "The role of interstellar dust is noted as a potential factor affecting luminosity density estimates, particularly if extinction is luminosity-dependent.",
    ],
    "10.3847/1538-4357/aa9ced": [
        "Two distinct stellar populations in the Galactic halo were identified based on their α-to-iron abundance ratios, referred to as High-Mg (HMg) and Low-Mg (LMg) populations.",
        "The HMg population exhibits higher [α/Fe] ratios compared to the LMg population, indicating different chemical enrichment histories.",
        "The metallicity range covered in this study (−2.2 < [Fe/H] < +0.5) is broader than previous works, revealing the knee in the [α/Fe] vs. [Fe/H] trend for both populations at [Fe/H] ∼ −0.4 (HMg) and [Fe/H] ∼ −1.0 (LMg).",
        "The HMg population shows a steeper decline in [α/Fe] at higher metallicities, attributed to the contribution of Type Ia supernovae (SN Ia).",
        "The LMg population has a flatter slope in [Mg/Fe] vs. [Fe/H] compared to other α-elements, suggesting different nucleosynthetic origins or IMF effects.",
        "The upper mass limit (M_up) of the initial mass function (IMF) was inferred to be higher for the HMg population (25–40 M⊙) compared to the LMg population (10–20 M⊙).",
        "The star formation rate (SFR) was more intense and longer-lived for the HMg population, while the LMg population had a lower and shorter SFR.",
        "The fraction of Type Ia supernovae (SN Ia) contributing to the ISM enrichment was similar for both populations, with no significant difference detected.",
        "The spatial distribution of the HMg population is concentrated in the inner halo, while the LMg population extends to larger distances from the Galactic center and plane.",
        "The chemical differences between the two populations are explained by a combination of a top-heavier IMF for the HMg population and the earlier onset of SN Ia enrichment in the LMg population.",
        "The results suggest an inside-out formation scenario for the Galactic halo, with the HMg population forming first in the inner regions and the LMg population forming later in the outer regions.",
        "The dispersion in abundance ratios for the LMg population indicates possible contributions from multiple subpopulations or stochastic pollution from massive stars in metal-poor environments.",
    ],
    "10.1126/science.1209840": [
        "Ubiquitous, large (150-kiloparsec) halos of ionized oxygen surround star-forming galaxies, detected using the Cosmic Origins Spectrograph onboard the Hubble Space Telescope.",
        "Star-forming galaxies exhibit significantly more ionized oxygen in their circumgalactic medium (CGM) compared to passive galaxies with little or no star formation.",
        "The ionized CGM contains a substantial mass of heavy elements and gas, potentially exceeding the reservoirs of gas within the galaxies themselves.",
        "The presence of ionized oxygen in the CGM is strongly correlated with specific star formation rate (sSFR), indicating a direct link between star formation and CGM properties.",
        "The CGM oxygen mass around star-forming galaxies is estimated to be at least 1.2 × 10^7 solar masses, representing 10-70% of the interstellar medium (ISM) oxygen mass.",
        "The total mass of circumgalactic gas could be comparable to or exceed the ISM gas mass, depending on metallicity and ionization conditions.",
        "The O VI absorption features are closely associated with the galaxies in velocity space, suggesting the gas is gravitationally bound and not escaping the halo.",
        "The dichotomy between star-forming and passive galaxies is reflected in their CGM, with passive galaxies showing less ionized oxygen, likely due to processes that quench star formation.",
        "The CGM may serve as a major reservoir for metals ejected from galaxies, influencing galactic chemical evolution and the mass-metallicity relation.",
        "The findings challenge theoretical models to explain the ubiquity of massive, metal-enriched halos around star-forming galaxies and the fate of these metals after star formation ends.",
    ],
    "10.1086/300959": [
        "The universal rest-frame ultraviolet luminosity density declines gradually from z=1 to the present, with a shallower slope (approximately (1+z)^1.5 for q_0=0.5) than previously reported by Lilly et al.",
        "Galaxy formation is found to continue smoothly to the present time rather than peaking at z=1, with much of the current formation occurring in smaller galaxies.",
        "The study uses a large, deep, and highly complete spectroscopic redshift survey with multicolor data (U', B, V, R, I, J, HK') to select samples based on rest-frame ultraviolet magnitudes, avoiding extrapolation errors.",
        "The rest-frame UV luminosity density at low redshifts is higher than previously estimated by Lilly et al., aligning more closely with the local UV luminosity density determined by Treyer et al. (1998).",
        "The shape of the UV luminosity function remains consistent across redshifts, suggesting pure luminosity evolution without significant changes in the function's shape.",
        "Comparisons with the CFRS data show a much shallower decline in UV luminosity density, likely due to the CFRS's reliance on extrapolations from redder wavelengths.",
        "The rest-frame red luminosity (8000 Å) exhibits very weak evolution with redshift, contrasting with the more pronounced evolution in the UV.",
        "The integrated star formation rate continues to rise smoothly at low redshifts, implying that the bulk of star formation has occurred at recent times rather than at z=1.",
        "The study highlights the importance of uniform sample selection and deep observations to minimize errors from dust and incomplete luminosity function sampling.",
        "Systematic and statistical errors are carefully accounted for, with photometric comparisons showing consistency between the HDF and wider field data, though clustering effects cause minor variations.",
    ],
    "10.1086/308692": [
        "Far-infrared (FIR) photometry at 150 and 205 μm of eight low-redshift starburst galaxies was obtained using ISO ISOPHOT, with five galaxies detected in both wavebands.",
        "The FIR spectral energy distributions (SEDs) are best fitted by a combination of two modified Planck functions, with warm dust (T~40-55 K) and cool dust (T~20-23 K), and a dust emissivity index ɛ=2.",
        "Cool dust can contribute up to 60% of the total FIR flux in starburst galaxies and is heated by both the general interstellar radiation field and the starburst itself.",
        "The cool dust mass is up to ~150 times larger than the warm dust mass, bringing gas-to-dust ratios close to Milky Way values when rescaled for metallicity.",
        "The ratio between total dust FIR emission (1-1000 μm) and IRAS FIR emission (40-120 μm) is ~1.75, about 40% larger than previously inferred from millimeter data.",
        "Despite being classified as UV-bright, four galaxies have UV energy (shortward of 0.2 μm) less than 15% of their FIR energy, with ~30% of bolometric flux emitted in UV-to-near-IR and the rest in FIR.",
        "Energy balance calculations show FIR emission predicted by dust reddening of UV-to-near-IR stellar emission is within a factor of ~2 of observed values in individual galaxies and within 20% when averaged over a sample.",
        "If local starbursts are representative of high-redshift UV-bright galaxies, their FIR emission may be undetected in submillimeter surveys unless their bolometric luminosity is comparable to ultraluminous FIR galaxies and their SED contains a cool dust component.",
        "The starburst obscuration curve, with a zero point R'_V=4.05±0.80, accurately predicts dust opacity in UV-bright star-forming galaxies within ~20% for large samples.",
        "High-redshift galaxies with SEDs similar to local starbursts like NGC 6090 may be detectable with current submillimeter instrumentation if their bolometric luminosities are ≥10^12 L⊙, but those with SEDs like Tol 1924−416 may remain undetected.",
    ],
}
