findings = {
    "10.1086/309975": [
        "The comoving luminosity density of the universe increases with redshift in all three observed wave bands (2800 A, 4400 A, and 1 mu m).",
        "For a (q0 = 0.5, Omega = 1.0) cosmological model, the comoving luminosity density increases as (1 + z)^2.1 +/- 0.5 at 1 mu m, (1 + z)^2.7 +/- 0.5 at 4400 A, and (1 + z)^3.9 +/- 0.75 at 2800 A.",
        "The exponents for luminosity density evolution are reduced by 0.43 and 1.12 for (0.05, 0.1) and (-0.85, 0.1) cosmological models, respectively.",
        "The observed luminosity density evolution can be modeled by an actively evolving stellar population with a Salpeter initial mass function (IMF) extending to 125 M⊙ and a star formation rate declining as tau^-2.5.",
        "A Scalo IMF extending to the same mass limit produces too many long-lived low-mass stars and does not fit the observed data as well.",
        "The rapid evolution of the star formation rate and comoving luminosity density agrees with conclusions from analyses of the evolving metallicity of the universe.",
        "The physical luminosity density at short wavelengths has likely declined by 2 orders of magnitude since z ~ 1.",
        "The global star formation rate at z ~ 1 was 15 times higher for (0.5, 1.0), 11 times higher for (0.05, 0.1), and 7 times higher for (-0.85, 0.1) cosmological models, with uncertainties of about 0.22 in the log.",
        "The physical luminosity density at 2800 Å has declined by a factor of 60–170 since z ~ 1 for a (0.5, 1.0) model, with a factor of 2 reduction in the extreme (-0.85, 0.1) model.",
    ],
    "10.1086/300959": [
        "The study finds a shallower decline in the universal rest-frame ultraviolet (UV) luminosity density from z=1 to the present, approximately (1+z)^1.5 for q_0=0.5, contradicting the steeper evolution reported by Lilly et al.",
        "The results suggest that galaxy formation continues smoothly to the present time rather than peaking at z=1, with much of the current formation occurring in smaller galaxies.",
        "The UV luminosity density at low redshifts is considerably higher than previously estimated by Lilly et al., aligning more closely with the local UV luminosity density determined by Treyer et al.",
        "The analysis uses a deep, multi-color spectroscopic redshift survey to avoid extrapolation issues present in previous studies, providing more accurate rest-frame UV luminosity measurements.",
        "The study compares luminosity functions at different rest-frame wavelengths (1700 Å, 2250 Å, 2750 Å) and finds only weak sensitivity to wavelength choice, supporting the robustness of the results.",
        "The 2500 Å rest-frame luminosity density evolution is well-described by a (1+z)^1.5 power law, indicating a slower decline in star formation activity than previously thought.",
        "Comparisons with the Treyer et al. local UV sample show consistent luminosity densities, further supporting the shallower evolution slope.",
        "The study highlights discrepancies with the Lilly et al. CFRS analysis, attributing them to methodological differences and extrapolation uncertainties in the CFRS data.",
        "The rest-frame red luminosity (8000 Å) shows minimal evolution from z=0.5 to z=1, contrasting with the more significant evolution observed in the UV.",
        "The findings imply that the bulk of star formation has occurred at more recent times, challenging the notion that the peak epoch of galaxy formation was at z=1.",
    ],
    "10.3847/1538-4357/aa6007": [
        "The CGM of field L* galaxies exhibits a declining H I surface density with impact parameter R⊥ at >99.5% confidence.",
        "The transmission of ionizing radiation through CGM gas alone is 70 ± 7%.",
        "The metallicity distribution function of the cool CGM is unimodal with a median of 10^-0.51 Z⊙ and a 95% interval ≈1/50 Z⊙ to >3 Z⊙.",
        "The incidence of metal-poor (<1/100 Z⊙) gas is low, implying any such gas discovered along quasar sightlines is typically unrelated to L* galaxies.",
        "An unexpected increase in gas metallicity with declining N_HI (at >99.9% confidence) and, therefore, also with increasing R⊥ was found; the high metallicity at large radii implies early enrichment.",
        "A non-parametric estimate of the cool CGM gas mass is M_CGM^cool = (9.2 ± 4.3) × 10^10 M⊙, which together with new mass estimates for the hot CGM may resolve the galactic missing baryons problem.",
        "The CGM of field L* galaxies is generally enriched above ~10% solar, with a broad metallicity distribution indicating significant scatter.",
        "At least a subset of the CGM surrounding field L* galaxies has super-solar metallicity, with 15% of systems having 90% of their metallicity PDFs above solar.",
        "An anti-correlation between N_HI and metallicity was observed, suggesting higher metallicity at lower N_HI and larger impact parameters.",
        "The cool CGM gas mass estimate suggests it is a major reservoir of baryons, potentially rivaling the condensed baryonic matter in galaxies.",
    ],
    "10.1111/j.1365-2966.2009.14750.x": [
        "Models of the chemical evolution of the Galaxy are extended to include radial migration of stars and flow of gas through the disc.",
        "The models track the production of both iron and α-elements.",
        "A model is chosen that provides an excellent fit to the metallicity distribution of stars in the Geneva-Copenhagen survey (GCS) of the solar neighbourhood.",
        "The model provides a good fit to the distribution of GCS stars in the age-metallicity plane, although this plane was not used in the fitting process.",
        "The model's star formation rate is monotonically declining, yet its disc naturally splits into an α-enhanced thick disc and a normal thin disc.",
        "The model's distribution of stars in the ([O/Fe], [Fe/H]) plane resembles that of Galactic stars, displaying a ridge line for each disc.",
        "The thin-disc's ridge line is entirely due to stellar migration, with characteristic variation of stellar angular momentum along it.",
        "Radial mixing of stellar populations with high σz from inner regions of the disc to the solar neighbourhood explains the steeper increase of σz with age than predicted by theory.",
        "The metallicity gradient in the interstellar medium is predicted to be steeper than in earlier models, but appears to be in good agreement with data for both our Galaxy and external galaxies.",
        "The models are inconsistent with a cut-off in the star formation rate at low gas surface densities.",
        "The absolute magnitude of the disc is given as a function of time in several photometric bands, and radial colour profiles are plotted for representative times.",
        "The dichotomy between the thin and thick discs arises naturally from the model without requiring breaks in star formation history or accretion events.",
        "The model reproduces the observed correlations between metallicity and stellar kinematics in the solar neighbourhood.",
        "The vertical density profile of the disc can be represented as the sum of two exponentials, corresponding to the thin and thick discs.",
        "The model predicts a steeper metallicity gradient in the gas than in the stars, due to radial gas flows and mixing.",
        "The age-velocity dispersion relation in the solar neighbourhood is explained by radial migration bringing stars born in the inner disc to the solar neighbourhood.",
    ],
    "10.1086/311708": [
        "A flat distribution of the comoving UV luminosity density is statistically indistinguishable from a peaked distribution at z~1.5 when errors, especially sampling error, are properly accounted for.",
        "Applying a uniform surface brightness cut reveals that the UV luminosity density from high intrinsic surface brightness regions increases by almost 2 orders of magnitude from z~0 to z~5.",
        "There exists a population of high-redshift objects with very high star formation rates that are not present at low redshifts.",
        "The peak of star formation likely occurs beyond z>2, contrary to previous suggestions of a peak at z~1.5.",
        "Sampling error dominates the uncertainty in UV luminosity density measurements, and previous analyses underestimated this uncertainty.",
        "The M98 Lyman break galaxy selection method may miss up to 50% of high-redshift galaxies in the Hubble Deep Field.",
        "Cosmological surface brightness dimming significantly affects UV luminosity density measurements, with high-redshift observations sampling only the highest surface brightness regions.",
        "The ratio of UV luminosity density from high surface brightness regions to total UV luminosity density is much higher at high redshifts than at low redshifts, suggesting a strongly increasing UV luminosity density with redshift.",
    ],
    "10.1093/mnras/283.4.1388": [
        "The Lyman decrement associated with HI in QSO absorption systems provides a distinctive feature for identifying galaxies at z > 2.5.",
        "Colour criteria sensitive to the Lyman continuum break can successfully identify star-forming galaxies at 3 < z < 3.5, as confirmed by Keck spectroscopy.",
        "The Hubble Deep Field (HDF) observations allow for statistical constraints on the redshift distribution of galaxies to fainter limits than current spectroscopic limits.",
        "A model of HI cosmic opacity as a function of redshift, including Lyman series scattering and Lyman continuum absorption, was developed.",
        "Stellar population synthesis models with varied ages, metallicities, dust contents, and redshifts were used to derive robust colour selection criteria for high-redshift galaxies.",
        "A sample of star-forming galaxies at 2 < z < 4.5 was constructed from HDF images using these colour criteria.",
        "The colour criteria effectively selected galaxies at 2.6 < z < 3.2 without contamination from low-redshift galaxies (0 < z < 1.4).",
        "The ultraviolet dropout technique enables investigation of cosmic star and element formation in the early Universe.",
        "A lower limit to the heavy element ejection rate from Type II supernovae at <z> = 2.75 was set at ~3.6 x 10^-4 M_solar yr^-1 Mpc^-3 (for q_0 = 0.5, H_0 = 50 km s^-1 Mpc^-1).",
        "The metal ejection rate at <z> = 2.75 is 3 times higher than the local value but 4 times lower than the rate at z ~ 1.",
        "At <z> = 4, the lower limit to the cosmic metal ejection rate is ~3 times lower than the <z> = 2.75 value.",
        "The results have implications for models of galaxy formation and the chemical enrichment and ionization history of the intergalactic medium.",
    ],
    "10.48550/arXiv.2203.02041": 
}
