CREATE DATABASE citeline_db;
GRANT ALL PRIVILEGES ON DATABASE citeline_db TO bbasseri;
\c citeline_db
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO bbasseri;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO bbasseri;