dataset_path: data/dataset/nontrivial_checked.jsonl
embedder: Qwen/Qwen3-Embedding-0.6B
db_collection: qwen06_chunks
query_expansions: 
  - identity
  - add_prev_2
embedder: Qwen/Qwen3-Embedding-0.6B
output_path: data/nn_datasets/addprev02_orig_dataset/